# Generated by Django 4.2.11 on 2024-04-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.RemoveField(
            model_name='workout',
            name='calories_burned',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout_management.exercise'),
        ),
        migrations.AddField(
            model_name='workout',
            name='numberOfReps',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workout',
            name='setnumber',
            field=models.TextField(default='Set 1'),
        ),
        migrations.AddField(
            model_name='workout',
            name='time',
            field=models.TimeField(default='06:00'),
        ),
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=4),
        ),
        migrations.DeleteModel(
            name='Goals',
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
        migrations.DeleteModel(
            name='PaymentDetail',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
