# Generated by Django 4.2.11 on 2024-05-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_management', '0003_alter_workout_user_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date', '-start_time']},
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='workout',
            name='start_time',
            field=models.TimeField(default='06:00'),
        ),
    ]
