# Generated by Django 4.2.11 on 2024-05-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_management', '0004_alter_workout_options_rename_time_workout_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='numberOfReps',
            new_name='number_of_reps',
        ),
    ]
