# Generated by Django 4.2.11 on 2024-05-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_management', '0005_rename_numberofreps_workout_number_of_reps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={},
        ),
        migrations.AlterField(
            model_name='workout',
            name='setnumber',
            field=models.TextField(default='1'),
        ),
    ]
